# Generated by Django 4.2.11 on 2025-12-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='object_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
